/**
 * 稳定错误码与统一错误响应格式。
 * 前端通过 error.code 分支，禁止用字符串判断错误类型。
 */

export const ERROR_CODES = {
  // 通用
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  NOT_FOUND: 'NOT_FOUND',
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',
  RATE_LIMITED: 'RATE_LIMITED',
  CONFLICT: 'CONFLICT',

  // Auth
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  EMAIL_ALREADY_REGISTERED: 'EMAIL_ALREADY_REGISTERED',
  USER_DISABLED: 'USER_DISABLED',
  SESSION_EXPIRED: 'SESSION_EXPIRED',
  TURNSTILE_VERIFICATION_FAILED: 'TURNSTILE_VERIFICATION_FAILED',
  TURNSTILE_NOT_CONFIGURED: 'TURNSTILE_NOT_CONFIGURED',
  AGREEMENT_REQUIRED: 'AGREEMENT_REQUIRED',
  AGREEMENT_OUTDATED: 'AGREEMENT_OUTDATED',
  REGISTRATION_DISABLED: 'REGISTRATION_DISABLED',
  EMAIL_DOMAIN_NOT_ALLOWED: 'EMAIL_DOMAIN_NOT_ALLOWED',
  EMAIL_DOMAIN_REGISTRATION_LIMIT: 'EMAIL_DOMAIN_REGISTRATION_LIMIT',
  INVITATION_CODE_REQUIRED: 'INVITATION_CODE_REQUIRED',
  INVITATION_CODE_INVALID: 'INVITATION_CODE_INVALID',
  PASSWORD_RESET_DISABLED: 'PASSWORD_RESET_DISABLED',

  // Workspace / 权限
  IDOR_FORBIDDEN: 'IDOR_FORBIDDEN',
  WORKSPACE_NOT_FOUND: 'WORKSPACE_NOT_FOUND',
  NOT_WORKSPACE_MEMBER: 'NOT_WORKSPACE_MEMBER',

  // Generation
  GENERATION_NOT_FOUND: 'GENERATION_NOT_FOUND',
  GENERATION_INVALID_STATUS_TRANSITION: 'GENERATION_INVALID_STATUS_TRANSITION',
  GENERATION_ALREADY_SETTLED: 'GENERATION_ALREADY_SETTLED',

  // Billing
  INSUFFICIENT_CREDITS: 'INSUFFICIENT_CREDITS',
  NEGATIVE_BALANCE: 'NEGATIVE_BALANCE',
  LEDGER_IDEMPOTENCY_CONFLICT: 'LEDGER_IDEMPOTENCY_CONFLICT',
  PRICING_NOT_FOUND: 'PRICING_NOT_FOUND',

  // Entitlement / Limits (P1-2)
  CONCURRENCY_LIMIT_REACHED: 'CONCURRENCY_LIMIT_REACHED',
  DAILY_QUOTA_EXCEEDED: 'DAILY_QUOTA_EXCEEDED',
  MONTHLY_QUOTA_EXCEEDED: 'MONTHLY_QUOTA_EXCEEDED',
  MODEL_NOT_ALLOWED: 'MODEL_NOT_ALLOWED',
  RESOLUTION_NOT_ALLOWED: 'RESOLUTION_NOT_ALLOWED',
  GENERATION_TYPE_NOT_ALLOWED: 'GENERATION_TYPE_NOT_ALLOWED',
  VIDEO_DURATION_EXCEEDED: 'VIDEO_DURATION_EXCEEDED',
  NO_ACTIVE_SUBSCRIPTION: 'NO_ACTIVE_SUBSCRIPTION',

  // Settings (P1-4)
  SETTING_NOT_REGISTERED: 'SETTING_NOT_REGISTERED',
  SETTING_VERSION_CONFLICT: 'SETTING_VERSION_CONFLICT',

  // RBAC (P1-5)
  PERMISSION_DENIED: 'PERMISSION_DENIED',
  STEP_UP_REQUIRED: 'STEP_UP_REQUIRED',
  ROLE_NOT_FOUND: 'ROLE_NOT_FOUND',

  // Account lifecycle (P1-6)
  PASSWORD_RESET_TOKEN_INVALID: 'PASSWORD_RESET_TOKEN_INVALID',
  SESSION_NOT_FOUND: 'SESSION_NOT_FOUND',

  // Trial / Coupon (P1-8)
  COUPON_NOT_FOUND: 'COUPON_NOT_FOUND',
  COUPON_DISABLED: 'COUPON_DISABLED',
  COUPON_EXPIRED: 'COUPON_EXPIRED',
  COUPON_USAGE_LIMIT_REACHED: 'COUPON_USAGE_LIMIT_REACHED',
  COUPON_USER_LIMIT_REACHED: 'COUPON_USER_LIMIT_REACHED',
  COUPON_INVALID_FOR_ORDER: 'COUPON_INVALID_FOR_ORDER',

  // Provider / Credential
  PROVIDER_NOT_FOUND: 'PROVIDER_NOT_FOUND',
  CREDENTIAL_NOT_FOUND: 'CREDENTIAL_NOT_FOUND',
  NO_AVAILABLE_CREDENTIAL: 'NO_AVAILABLE_CREDENTIAL',
  PROVIDER_UPSTREAM_ERROR: 'PROVIDER_UPSTREAM_ERROR',
  PROVIDER_RATE_LIMITED: 'PROVIDER_RATE_LIMITED',
  PROVIDER_UNAUTHORIZED: 'PROVIDER_UNAUTHORIZED',
  PROVIDER_TIMEOUT: 'PROVIDER_TIMEOUT',
  CREDENTIAL_SECRET_INVALID: 'CREDENTIAL_SECRET_INVALID',

  // Security
  SSRF_BLOCKED: 'SSRF_BLOCKED',
  UPLOAD_INVALID: 'UPLOAD_INVALID',

  // Payment (Phase 7)
  PAYMENT_NOT_FOUND: 'PAYMENT_NOT_FOUND',
  PAYMENT_CHANNEL_NOT_CONFIGURED: 'PAYMENT_CHANNEL_NOT_CONFIGURED',
  PAYMENT_CALLBACK_INVALID: 'PAYMENT_CALLBACK_INVALID',
  PAYMENT_AMOUNT_MISMATCH: 'PAYMENT_AMOUNT_MISMATCH',
  PAYMENT_ORDER_NOT_PENDING: 'PAYMENT_ORDER_NOT_PENDING',
  PAYMENT_CREDITS_NOT_POSITIVE: 'PAYMENT_CREDITS_NOT_POSITIVE',
  PAYMENT_TX_REF_CONFLICT: 'PAYMENT_TX_REF_CONFLICT',
  PAYMENT_ALREADY_REFUNDED: 'PAYMENT_ALREADY_REFUNDED',
  PAYMENT_REFUND_NOT_ALLOWED: 'PAYMENT_REFUND_NOT_ALLOWED',
  MANUAL_REFUND_ALREADY_PROCESSED: 'MANUAL_REFUND_ALREADY_PROCESSED',
  MANUAL_REFUND_CREDITS_INSUFFICIENT: 'MANUAL_REFUND_CREDITS_INSUFFICIENT',
  EMAIL_SEND_FAILED: 'EMAIL_SEND_FAILED',
  EMAIL_NOT_CONFIGURED: 'EMAIL_NOT_CONFIGURED',

  // System Update / Rollback
  UPDATE_CHECK_FAILED: 'UPDATE_CHECK_FAILED',
  UPDATE_NOT_ENABLED: 'UPDATE_NOT_ENABLED',
  UPDATE_IN_PROGRESS: 'UPDATE_IN_PROGRESS',
  UPDATE_ALREADY_UP_TO_DATE: 'UPDATE_ALREADY_UP_TO_DATE',
  UPDATE_INVALID_VERSION: 'UPDATE_INVALID_VERSION',
  UPDATE_OPERATION_NOT_FOUND: 'UPDATE_OPERATION_NOT_FOUND',
  UPDATE_EXEC_FAILED: 'UPDATE_EXEC_FAILED',
} as const;
export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];

/**
 * 统一错误响应体：
 * { "error": { "code": "INSUFFICIENT_CREDITS", "message": "...", "requestId": "..." } }
 */
export interface ApiErrorBody {
  error: {
    code: ErrorCode | string;
    message: string;
    requestId?: string;
    details?: unknown;
  };
}

/** 底层为给定 Message/StatusCode 提供 stable error code 的领域异常基类。 */
export class DomainError extends Error {
  readonly code: ErrorCode | string;
  readonly statusCode: number;
  readonly details?: unknown;
  readonly requestId?: string;

  constructor(params: {
    code: ErrorCode | string;
    message: string;
    statusCode?: number;
    details?: unknown;
    requestId?: string;
    cause?: unknown;
  }) {
    super(params.message, params.cause ? { cause: params.cause } : undefined);
    this.name = 'DomainError';
    this.code = params.code;
    this.statusCode = params.statusCode ?? 500;
    this.details = params.details;
    this.requestId = params.requestId;
  }

  toBody(): ApiErrorBody {
    return { error: { code: this.code, message: this.message, requestId: this.requestId, details: this.details } };
  }
}

/** 便捷构造函数。 */
export function domainError(
  code: ErrorCode | string,
  message: string,
  statusCode = 500,
  details?: unknown,
): DomainError {
  return new DomainError({ code, message, statusCode, details });
}
